insert into user(head_image, name, phone, password, gender, create_time, update_time) values("https://img5.duitang.com/uploads/item/201412/07/20141207214303_hTT3P.jpeg","叶玉明","18681506437","e10adc3949ba59abbe56e057f20f883e",1,now(),now());
insert into admin_user(user_id,role,token,state)values(1,1,"0000",1);
insert into postage(area,price,post)values ("北京",0,0);insert into postage(area,price,post)values ("天津",0,0);
insert into postage(area,price,post)values ("河北",0,0);insert into postage(area,price,post)values ("山西",0,0);
insert into postage(area,price,post)values ("内蒙古",0,0);insert into postage(area,price,post)values ("辽宁",0,0);
insert into postage(area,price,post)values ("吉林",0,0);insert into postage(area,price,post)values ("黑龙江",0,0);
insert into postage(area,price,post)values ("上海",0,0);insert into postage(area,price,post)values ("江苏",0,0);
insert into postage(area,price,post)values ("浙江",0,0);insert into postage(area,price,post)values ("安徽",0,0);
insert into postage(area,price,post)values ("福建",0,0);insert into postage(area,price,post)values ("江西",0,0);
insert into postage(area,price,post)values ("山东",0,0);insert into postage(area,price,post)values ("河南",0,0);
insert into postage(area,price,post)values ("湖北",0,0);insert into postage(area,price,post)values ("湖南",0,0);
insert into postage(area,price,post)values ("广东",0,0);insert into postage(area,price,post)values ("广西",0,0);
insert into postage(area,price,post)values ("海南",0,0);insert into postage(area,price,post)values ("重庆",0,0);
insert into postage(area,price,post)values ("四川",0,0);insert into postage(area,price,post)values ("贵州",0,0);
insert into postage(area,price,post)values ("云南",0,0);insert into postage(area,price,post)values ("西藏",0,0);
insert into postage(area,price,post)values ("陕西",0,0);insert into postage(area,price,post)values ("甘肃",0,0);
insert into postage(area,price,post)values ("青海",0,0);insert into postage(area,price,post)values ("宁夏",0,0);
insert into postage(area,price,post)values ("新疆",0,0);insert into postage(area,price,post)values ("台湾",0,0);
insert into postage(area,price,post)values ("香港",0,0);insert into postage(area,price,post)values ("澳门",0,0);